### ISSUE TITLE
How to generate private key?

### ISSUE THREAD

**Issue by yupnano** [Bit-Wasp/secp256k1-php#108]
Hi, I am wondering how to generate private key with this ropo?

And in the example [create_public_key.php](https://github.com/Bit-Wasp/secp256k1-php/blob/master/examples/create_public_key.php#L5) , there is a comment: `//Private keys are never generated by secp256k1.`   Then how could I generate a private key? 

Thanks for any information!

And by the way, could I use this library whth composer? I didn't find the "composer require" information for this library.

**Comment by afk11** [comment]
Private keys are random bytes. You can test the keys validity with `secp256k1_seckey_verify`

This library is a C extension. You'll need to build it via the command line.

**Comment by yupnano** [comment]
Thank you for the replay. I thought that this is a pure PHP library.
