### ISSUE TITLE
这个是什么问题啊

### ISSUE THREAD

**Issue by wapele** [Bit-Wasp/secp256k1-php#128]
/www/wwwroot/b_com/secp256k1-php/secp256k1/secp256k1.c: 在函数‘zif_secp256k1_ecdh’中:
/www/wwwroot/b_com/secp256k1-php/secp256k1/secp256k1.c:1444:5: 错误：提供给函数‘secp256k1_ecdh’的实参太少
     result = secp256k1_ecdh(ctx, resultChars, pubkey, privKey->val);
     ^
In file included from /www/wwwroot/b_com/secp256k1-php/secp256k1/php_secp256k1.h:3:0,
                 from /www/wwwroot/b_com/secp256k1-php/secp256k1/secp256k1.c:11:
/usr/local/include/secp256k1_ecdh.h:42:48: 附注：在此声明
 SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_ecdh(
                                                ^
make: *** [secp256k1.lo] 错误 1

**Comment by afk11** [comment]
https://github.com/bitcoin/secp256k1 needs to be commit cd329dbc3eaf096ae007e807b86b6f5947621ee3 to work

https://github.com/Bit-Wasp/secp256k1-php/issues/124
