### ISSUE TITLE
error in benchmark.php

### ISSUE THREAD

**Issue by dan-da** [Bit-Wasp/secp256k1-php#36]
With a fresh git clone, as instructed in the README.

$time php -dextension=secp256k1.so ../benchmark.php > /dev/null

PHP Warning:  secp256k1_ecdsa_verify() expects exactly 4 parameters, 3 given in /home/websites/secp256k1-php/benchmark.php on line 8
<... warning repeats many times ...>

Looks like it is missing the initial context parameter.   But I tried adding that and got another error, so gave up for now.

(regardless, I can tell the library is working in bitcoin-php lib, because now my app is much faster.)

**Comment by afk11** [comment]
Seems to be working at the moment, thanks
