### ISSUE TITLE
Secp256k1 failed to parse public key

### ISSUE THREAD

**Issue by dan-da** [Bit-Wasp/secp256k1-php#37]
I am getting this error from my application somewhat erratically but frequently.  Once it starts to happen, it seems to be repeatable with successive executions for the same xpub.

If I disable the secp256k1 extension and run again without any code changes (using bitwasp/bitcoin-php lib) it always executes without fail.

So I get the feeling the extension is (randomly?) getting wedged into an unhappy state and then staying that way.

Sorry I do not have a simple test case at present.  If I find/devise one, I will attach it.

The xpub that failed in this particular case was:
xpub697odnriKgTgWE4my6au8nd8haUfAMzLGFpDemAkRbCMgGVxANuj9DffNLgDjPA1dnxzi8oFmM79ZPgKVfCV7Saj8sQUL7tJfeZDuyQNGDm

Output from my program with relevant stack trace was:
2015-12-30T16:34:28-08:00 [pid: 15973] [exception] -- #1: RuntimeException. code: 0. Secp256k1 failed to parse public key

/home/websites/hd-wallet-addrs/vendor/bitwasp/bitcoin/src/Crypto/EcAdapter/Impl/Secp256k1/Serializer/Key/PublicKeySerializer.php : 72

Stack Trace:
#0 /home/websites/hd-wallet-addrs/vendor/bitwasp/bitcoin/src/Key/PublicKeyFactory.php(33): BitWasp\Bitcoin\Crypto\EcAdapter\Impl\Secp256k1\Serializer\Key\PublicKeySerializer->parse('0374e53bc70054c...')
#1 /home/websites/hd-wallet-addrs/vendor/bitwasp/bitcoin/src/Serializer/Key/HierarchicalKey/HexExtendedKeySerializer.php(103): BitWasp\Bitcoin\Key\PublicKeyFactory::fromHex('0374e53bc70054c...', Object(BitWasp\Bitcoin\Crypto\EcAdapter\Impl\Secp256k1\Adapter\EcAdapter))
#2 /home/websites/hd-wallet-addrs/vendor/bitwasp/bitcoin/src/Serializer/Key/HierarchicalKey/HexExtendedKeySerializer.php(117): BitWasp\Bitcoin\Serializer\Key\HierarchicalKey\HexExtendedKeySerializer->fromParser(Object(BitWasp\Buffertools\Parser))
#3 /home/websites/hd-wallet-addrs/vendor/bitwasp/bitcoin/src/Serializer/Key/HierarchicalKey/ExtendedKeySerializer.php(43): BitWasp\Bitcoin\Serializer\Key\HierarchicalKey\HexExtendedKeySerializer->parse(Object(BitWasp\Buffertools\Buffer))
#4 /home/websites/hd-wallet-addrs/vendor/bitwasp/bitcoin/src/Key/Deterministic/HierarchicalKeyFactory.php(67): BitWasp\Bitcoin\Serializer\Key\HierarchicalKey\ExtendedKeySerializer->parse('xpub697odnriKgT...')

**Comment by dan-da** [comment]
one more clue.   I actually see different behavior in different shells/terminals.

For example I have some unit tests for my app.

Running in shell 1, testfile 1 and 2 pass, but 3 always fails.
Running in shell2, testfile 1, 2, and 3 pass but 4 always fails.

Both shells use same .bashrc, etc.  nothing obviously different.

Each testfile invokes my CLI php app in a '''new process'''.

Given that newly invoked processes keep failing in the same way, but differently depending on shell, I would guess it is related to something in the environment.   I hesitate to speculate further.   :=)

If I can find some time later I'll try building the extension with debug symbols and run in gdb.

**Comment by afk11** [comment]
Interestingly I got this too while testing a different travis build environment. It's also been reported here https://github.com/Bit-Wasp/bitcoin-php/issues/215

I'm not sure what the cause is yet, I don't get this at all through the command line, but a running the same script over apache2 triggers the exception.

**Comment by afk11** [comment]
I tried that case in apache2 once more and it's fine now.

Running over the cli with xdebug enabled (run Bit-wasp/bitcoin-php test cases with coverage) appears to trigger the issue..

**Comment by afk11** [comment]
Parsing that key doesn't fail for me. We're learning something, not sure what though..

**Comment by dan-da** [comment]
ok, not a solid test case exactly, but it *might* help you reproduce or at least it is a data point.

On my dev machine that is running php 5.6 I can reliably reproduce it by running the test harness from my utility <a href="https://github.com/dan-da/hd-wallet-addrs">hd-wallet-addrs</a>.   Instructions are provided in the README.md.

OS: Ubuntu 14.04.1 LTS
PHP: PHP 5.6.16-2+deb.sury.org~trusty+1 (cli)

note that PHP 5.5.x is stock on this OS, so I installed custom .debs from a PPA to get 5.6.  ( The extension was built with correct phpize for 5.6 )

I just installed secp256k1-php on a second machine running ubuntu 13.04 stock php 5.4 and all the test cases run without error each time.   ( tried 5 times. )

OS: Ubuntu 13.04
PHP: PHP 5.4.9-4ubuntu2.4 (cli) (built: Dec 12 2013 04:29:20)


Update!!  I wrote the above and then re-ran the test harnesses on my dev machine (php 5.6) in the exact same shell I was using yesterday/last night. To my great surprise, I was able to run the test harness fully 5 times without error, where yesterday it would always fail.    This makes me wonder if the issue is not somehow time/date related.  eg, perhaps seeding srand() with time somewhere?

**Comment by afk11** [comment]
Did you use ondrejs? I should have remembered, I definitely had issues with his in the past. Actually, it was possibly only when I used xdebug from there, no way it found it's way into Ubuntu's repositories?

**Comment by dan-da** [comment]
Yes it is ondrej's.     What sort of issues did you have?

Anyway, if/when I see the issue again I will fire up gdb to see if I can catch it in the act, or if that fails, try ubuntu's stock php instead.   Just now, I can't remember why I needed to upgrade to 5.6 anyway.

**Comment by afk11** [comment]
I emailed him over it, but the page for his builds say don't contact him with segfaults/breaks/issues unless you have a patch... so no reply to that one. His build has definitely given me trouble, I think I was half way through rewriting the library before I asked if it could be the PHP version.. I changed away from his (because of the above warning) and didn't have the issue again. 

I'm actually sort of happy, the test case @deweller provided doesn't crash on apache for me anymore. Might be worth checking your software is up to date, and let me know if it happens again.. If it goes as magically as it came, then I'd be inclined to blame that... Lets see how it goes!

**Comment by afk11** [comment]
Hi @dan-da, I was looking over this once against recently. I think the problem has been found in #46 - though I could only produce the error by enabling xdebug (ubuntu 14.04, PHP version 5.6.11+dfsg-(1ubuntu3.4)

For me, xdebug appeared to cause the pubkeylenit to be something other than the

**Comment by afk11** [comment]
Far as I know this has been fixed, please re-open if the problem arises for you

**Comment by dan-da** [comment]
I am seeing this issue again.  :-(    Any ideas?

2017-08-10T21:57:19-07:00 [pid: 14557] [exception] -- #1: RuntimeException. code: 0. Secp256k1 failed to parse public key

Fails on a productin machine:

# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

ALSO FAILS

PHP 7.1.8-2+ubuntu16.04.1+deb.sury.org+4 (cli) (built: Aug  4 2017 13:04:12) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.8-2+ubuntu16.04.1+deb.sury.org+4, Copyright (c) 1999-2017, by Zend Technologies

ALSO FAILS

PHP 5.6.31-1~ubuntu16.04.1+deb.sury.org+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies


( yes, I ran phpize for each, using update-alternatives for php, phpize, php-config)


But works on a dev machine which also runs xenial, but different point release:

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

php --version
PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15-0ubuntu0.16.04.4, Copyright (c) 1999-2017, by Zend Technologies

**Comment by afk11** [comment]
I'll take a look for this, I really thought it had gone away. I guess you have checked the key is fine on another machine or with phpecc, and the issue is

**Comment by dan-da** [comment]
yes, I tried a couple keys on the machine where it fails, and on the dev machine where it works.

Also, with this installation, it is 100% repeatable, not intermittent.   I have not yet witnessed a successful event.   Please let me know if you have any ideas for code changes I can try.

btw, I noticed that pubkeylen is defined as size_t again, so I tried changing that to int and also newpubkeylen, but the error still occurs.

**Comment by afk11** [comment]
I hate these bugs, but mind printing `php -m`? 

Which branch are you running, are you still on the same branch as last time? Any change in the PHP version since you deployed first and the issue happening today?

**Comment by dan-da** [comment]
I hate them too.  sorry!

So previously I was running on a dedicated server.   More recently I switched over to a virtual server running on Xen.  At that time I upgraded to ubuntu 16.04.2.   I *forgot* to install secp256k1-php and it was running that way for some time.  Yesterday I noticed that key generation was really slow (duh) so I 
installed it, and ran into these problems.  Note in my prev post that I tried php5.6, 7.0 and 7.1 with same results.  

That is why I get a feeling it is somehow connected to running in a xen virtual machine.   I've read that virtual machines do not have a good source of entropy, so I tried installing haveged daemon which is supposed to help with that, but no change.   Anyway, it seems that reading an xpub should be deterministic.

I haven't tried debugging with gdb yet.  That could be a next step, but I figured I'd check if you have any ideas first.

here is an example xpub that fails.  nothing special about it.
xpub6BfKpqjTwvH21wJGWEfxLppb8sU7C6FJge2kWb9315oP4ZVqCXG29cdUtkyu7YQhHyfA5nt63nzcNZHYmqXYHDxYo8mm1Xq1dAC7YtodwUR

for testing I added a flag to my program that will optionally load the secp256k1-php extension via dl('secp256k1.so').   With it unloaded the xpub works just fine.  But with it loaded I get the error.

--- from host that fails ---

note: secp256k1 is not present here because I have it disabled in production at the moment and for testing am loading with dl().  But initially I had it loaded via php.ini with same results.

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pgsql
Phar
posix
readline
Reflection
session
shmop
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
Zend OPcache
zlib

[Zend Modules]
Zend OPcache


------  and this from the host that works -----

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gettext
gmp
hash
iconv
json
libxml
mbstring
mcrypt
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
secp256k1
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache

**Comment by dan-da** [comment]
I think it would be worth testing the secp256k1 lib without the php extension.  any chance you could post a little code sample in C for how to parse an xpub?

**Comment by dan-da** [comment]
I tried running the secp256k1 tests on both hosts.   seems ok.

$ ./tests 
test count = 64
random seed = 6ac6331cabac52c52fd4e709bc99828e
random run = 9b873a9bf185a994a3ba34fa9a6952a7
no problems found

**Comment by dan-da** [comment]
result of "make test" in secp256k1-php:

```
=====================================================================
PHP         : /usr/bin/php5.6
PHP_SAPI    : cli
PHP_VERSION : 5.6.31-1~ubuntu16.04.1+deb.sury.org+1
ZEND_VERSION: 2.6.0
PHP_OS      : Linux - Linux osc.co.cr 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64
INI actual  : /home/danda/secp256k1-php/secp256k1/tmp-php.ini
More .INIs  :
CWD         : /home/danda/secp256k1-php/secp256k1
Extra dirs  :
VALGRIND    : Not used
=====================================================================
TIME START 2017-08-11 15:55:37
=====================================================================
PASS Check for secp256k1 presence [tests/001.phpt] 
=====================================================================
TIME END 2017-08-11 15:55:37

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   16
---------------------------------------------------------------------

Number of tests :    1                 1
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :    1 (100.0%) (100.0%)
---------------------------------------------------------------------
Time taken      :    0 seconds
=====================================================================
```

**Comment by dan-da** [comment]
I do not understand how this code is supposed to be working:

```
    public function parse($data)
    {   
        $buffer = (new Parser($data))->getBuffer();
        $binary = $buffer->getBinary();
        $pubkey_t = '';
        /** @var resource $pubkey_t */
        if (!secp256k1_ec_pubkey_parse($this->ecAdapter->getContext(), $binary, $pubkey_t)) {
            throw new \RuntimeException('Secp256k1 failed to parse public key');
        }
```

In particular, $pubkey_t is explicitly set to empty string, then passed as third arg to secp256k1_ec_pubkey_parse().  Okay, I would assume this means that $binary has the needed data and $pubkey_t will get the answer out, right?

But then inside zif_secp256k1_ec_pubkey_parse(), we have:

```
    if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "rz/S", &zCtx, &zPubKey, &pubkeyin) == FAILURE) {
        RETURN_FALSE;
    }

   ...

    pubkey = emalloc(sizeof(secp256k1_pubkey));
    result = secp256k1_ec_pubkey_parse(ctx, pubkey, pubkeyin->val, pubkeyin->len);
    if (result) {
        ZVAL_NULL(zPubKey);
        ZVAL_RES(zPubKey, zend_register_resource(pubkey, le_secp256k1_pubkey));
    }
```

I notice a few things here:

1. In online docs I've reviewed for zend_get_parameters, lowercase s is used instead of capital S.   maybe doesn't matter, or is undocumented?

2. pubkeyin->val is empty because $pubkey_t was empty string.

3. pubkey is blank buffer.  We just emalloc'ed it.  zPubKey is only used afterwards to set result.

Therefore, the only thing we are really passing to secp256k1_ec_pubkey_parse() is the context var ctx.

So I would expect this call to fail, which it does.

I'm more confused as to (a) what is the intent here, and (b) how it is succeeding on the other machine?

**Comment by dan-da** [comment]
I just did a composer update, and now the args have reversed themselves to:
```
if (!secp256k1_ec_pubkey_parse($this->ecAdapter->getContext(), $pubkey_t, $binary,)) {
```

which makes more sense.  But I stil get the error.  I will continue investigating with gdb.

**Comment by dan-da** [comment]
Success!!!!

In my recent testing I had changed the "S" in zend_get_parameters to an "s", but forgot to change it back after the composer update.  When I fixed this and recompiled it works perfectly.

So my whole issue boiled down to using an older version and forgetting to run composer update.

Sorry for wasting your time!

**Comment by afk11** [comment]
Re make test, yeah that's snake oil, I should really add some tests to that folder. It's a generated sample test file, but doesn't touch the extension yet. 

So it was just a deployment mixup? I've often wondered if specifically committing a version in bitcoin-php could contribute to confusion here..

Re passing of string variables to pubkey_parse.. no reason they're strings in particular, but they written to as references by the extension if the function returns successful. null would probably also do..
