### ISSUE TITLE
When will this project support PHP7?

### ISSUE THREAD

**Issue by realpg** [Bit-Wasp/secp256k1-php#45]
Do you have a schedule?

**Comment by afk11** [comment]
I'll hopefully have a prototype next week, I'll was planning to do this to bitcoinconsensus-php first as it's a smaller codebase.

**Comment by afk11** [comment]
Ok, bitcoinconsensus-php was already compatible with PHP7, so was no help in easing me into things :) PHP7 support was merged into master today, and tagged as `v0.1`. Let me know if there's any problems, testing this with some applications now.

**Comment by afk11** [comment]
This was tagged a while ago, if you check branches you'll see an PHP5.x support branch, and the newest stuff is PHP7.
