### ISSUE TITLE
The tests take forever to start..

### ISSUE THREAD

**Issue by afk11** [Bit-Wasp/secp256k1-php#6]
I read that travis lets you use container based builds, which are quicker to start up. Apparently it decides this based on whether you use sudo - which we do to install the libsecp256k1 library. 

If we can avoid running `sudo make install` somehow hopefully we'll see some speed in the run time :/

**Comment by rubensayshi** [comment]
hmm you can probably `php -dextension=/full/path/to/secp256k1.so`

then we only need to change the `./configure` to be able to find libsecp256k1 files without them being installed 

and I took the `sudo apt-get install -qq libssl-dev` from the .travis.yml from libsecp256k1, but idk if it's really neccesary ...

**Comment by afk11** [comment]
This seems to be ok - recently I noticed the concurrent builds setting was set to 1.. things seem to be running decently now :)
